### ISSUE TITLE
Cannot import azure providers

### ISSUE THREAD

**Issue by bigg01** [Jsoconno/architectures#102]
**Describe the bug**
If I take the example with azure provider it looks like modules are not found.

**To Reproduce**
1. python -v venv myenv
2. source  myenv/bin/active
3. pip install  architectures graphviz
3. python arch1.py
```sh
Traceback (most recent call last):
  File "arch1.py", line 4, in <module>
    from architectures.providers.azure.ai import CognitiveServices
ModuleNotFoundError: No module named 'architectures.providers.azure'
```

**Expected behavior**
Import providers 

**Desktop (please complete the following information):**
 - OS:Fedora
 - python : Python 3.9.6 (default, Jul 16 2021, 00:00:00) 
 - Version 34

**Comment by Jsoconno** [comment]
Hi @bigg01.  Thanks for the feedback!  I was able to replicate this issue and it appears when the package is published to PyPi it does not include the provider folders.  I tested adding an __init__.py file to each to see if that would allow them to be discovered as packages as part of the publishing process, but that did not seem to work.

I'm in the middle of a life changing even with my second child just being born (sorry about the delayed response), but once I come off of FMLA / PTO I will look into this a bit more.

**Comment by Jsoconno** [comment]
@bigg01

I was able to fix this issue and a few more so thank you so much for the input!  It is making our package better.

The major changes were:

* Adding `__init__.py` files to each of the providers so that `setuptools.find_packages()` could find and ship them
* Adding a `MANIFEST.in` file to recursively include all static content (i.e. icon png files)
* Adding an `__init__.py` file to the icons folder so they will install when running `pip install architectures`
* Adding the `install_requires` attribute to `setup.py` so that graphviz is automatically installed since i saw you were having to run `pip install architectures graphviz`

Please let me know as you test this if you come across any issues.  At this point, I was able to resolve all of the issues stated as part of release 0.2.7 and test locally with similar steps to yours.  The release number jumped up so much because I created a lot of unstable releases along the way before going to test.pypi.org for testing.

Thanks again!
